name: "Build and Push Docker Image"
description: "action compose where build, tag and push docker image"
inputs:
  image-tag:
    description: "Example: latest or 3.14.3"
    required: true
  repository-name:
    description: "Docker Repository. Example: docker.io/bitnami/redis."
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      shell: bash
      run: |
        docker build --tag ${{ inputs.repository-name }}:${{ inputs.image-tag }} .

    - name: Push Docker image
      shell: bash
      run: |
        docker push ${{ inputs.repository-name }}:${{ inputs.image-tag }}