# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build-Test

on:
  workflow_dispatch:
    inputs:
      generateCLI:
        type: boolean
        description: "Generate top_numbers CLI"
        default: false
        required: true

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build CLI
        working-directory: sre-cli-tool
        if: ${{ inputs.generateCLI == 'true' }}
        run: go build -o top_numbers

      - name: Build
        working-directory: sre-cli-tool
        if: ${{ inputs.generateCLI == 'false' }}
        run: go build -v .

      - name: Test
        working-directory: sre-cli-tool
        run: go test -v .

      - name: 'Upload Artifact'
        if: ${{ inputs.generateCLI == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: top_numbers
          path: sre-cli-tool/top_numbers
          retention-days: 1