name: Generate CLI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build CLI
        working-directory: sre-cli-tool
        run: go build -o top_numbers

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: top_numbers
          path: sre-cli-tool/top_numbers
          retention-days: 1
